### ISSUE TITLE
[Soulbound System] Tracking Wounds

### ISSUE THREAD

**Issue by moo-man** [moo-man/AoS-Soulbound-FoundryVTT#82]
Admittedly, the rules for tracking wounds seems overly complex (compared to rest of the damage rules), but there is no need to track the type of Wound for every wounds, only for the Wound that causes a character to be Mortally Wounded (needs check box for Mortally Wounded that also add Stunned Condition). The rest of the Wounds should just be recorded as a number. This is relevant because when a character is healed and they have to remove one space on the wound track, they are not removing the Wound (which could fill 1 to 3 spaces on the wound track), but just wound (leaving only one space). As currently presented, if you had 4 spaces and suffered 2 Serious Wounds, you would appear as 6/4 wounds (but you should only show 4/4). If you remove the last space, you would be 3/4 wounds, but at the moment would would need to change the last Serious Wound to a Minor Wound to create the correct wound track status. This seems overly complex way of tracking the most complex aspect of the game. I suggest a quick dialog box when you add a wound that says what type of wound (so it can calculate the number of wounds on the wound track, but if that number would exceed the number of spaces it caps at the total spaces. You would then a function to generate a Death Test based on last Wound.<br/>**From**: TrickyDUK #3037<br/>age-of-sigmar-soulbound: 4.0.0<br/>soulbound-core: 1.0.0

**Comment by Kasyks** [comment]
Yes, when you heal a wound in natural way by Rest, then you dont need a type of wound - just heal 1 point from track. But when you will use for exp. Medic talent then you have to know a type of wound because the test will depend on it.
Additional to that Medic talent do not heal Minor wound so if you have only a sum of wounds you dont know which one is a Minor.  

From Medic talent:
"....You can only treat one Wound at a time, so if the ally has multiple Wounds you must tell the GM which Wound you are treating. To adequately treat the Wound you must succeed on a Mind (Medicine) Test. The DN of the Test is determined by the type of Wound you are trying to treat
A Severe Wound: DN 4:2
A Deadly Wound: DN 4:3 

If you succeed on the Test, the ally’s Wound severity reduces two steps instead of one at the end of the Rest. This means a Severe Wound is completely healed, and a Deadly Wound is reduced to a Minor Wound. If you fail the Test, your ally’s Wounds do not heal at all. Your failed attempts to heal them means they do not gain the benefits of a Rest."

So in my opinion wounds should have a type like it is now, not only the last one.

**Comment by moo-man** [comment]
So if the wound system should not be changed, what is this issue stemming from? It mentions 
> As currently presented, if you had 4 spaces and suffered 2 Serious Wounds, you would appear as 6/4 wounds (but you should only show 4/4)
I'm not sure I understand this, 2 Serious Wounds shows up as 4 Wounds on the counter.

**Comment by Kasyks** [comment]
I dont see this anomaly. I just hit my test 3 times by 5 dmg  when 0 toughness so each time test get deadly wound(3) I have this. For me all is correct.
![image](https://user-images.githubusercontent.com/88081888/145684517-14f759f4-94e6-4ed9-92fc-98a7828aa8a4.png)

Second hit has only 2 wound(because only 2 left after first hit), and the third has 0 wounds(because nothing left after first two hits). and the counter is 5/5 not 9/5

**Comment by TrickyDUK** [comment]
I have realised that this only happens when you add Wounds using the '+' button. When you use this function you get a drop down to select the severity of the wound and this automatically assigns a value of 1,2 or 3 respectively, which you cannot amend manually.
![image](https://user-images.githubusercontent.com/17655647/145694780-e768c998-f869-4c14-bb70-fb2c1c4ca1c2.png)

**Comment by moo-man** [comment]
I am still not able to reproduce this. The + button is the standard way of adding Wounds. Changes to the wound type reflects the total wound count

https://user-images.githubusercontent.com/28637157/145694898-fe124368-dd05-4cc0-929b-67c39eaf95db.mp4

Can you provide your exact reproduction steps

**Comment by TrickyDUK** [comment]
If you apply damage from the Chat card to the Actor, then the damage correctly reduces Toughness (to zero) and then starts to add Wounds (up to the max Wound value). But if you click the + button then you get a new Wound, select Wound Type and the Wounds value is automatically calculated as a fixed value, which may take the Wounds over the maximum.
By adding damage from Chat Card:
![image](https://user-images.githubusercontent.com/17655647/145695717-07de3d89-8470-4f86-9e62-034f3c6a6d52.png)
By adding from + button:
![image](https://user-images.githubusercontent.com/17655647/145695729-e0b2ebfb-b722-47ba-9840-be33133021a4.png)
Does that help?

**Comment by TrickyDUK** [comment]
Also, there needs to be a way to change this:
![image](https://user-images.githubusercontent.com/17655647/145783256-c6af911c-9657-4b43-8b7c-ac6507a6d9bd.png)
to this:
![image](https://user-images.githubusercontent.com/17655647/145783415-3597dfde-8a7c-455b-9b0f-42cc2e595e53.png)
When healing is applied that just clear the 1 wound from the wound track.
Basically, need to be edit the value of the wound independently from the type of wound.

**Comment by Vendare** [comment]
> I am still not able to reproduce this. The + button is the standard way of adding Wounds. Changes to the wound type reflects the total wound count
> 
>  dfFpadDKf9.mp4 
> Can you provide your exact reproduction steps

The whole "Wound System" is still in a semi optiomal place right now. Wounds used to be Items. These were deprecated and transformed to Objects added to the Actors Datafields. The ApplyDamage() function was build around those initial items and added wounds with apporiate values depending on the current wound Track. If the new wound would not or exactly fill the wound slot it will retain it's normal value. If the Value of the Wound is higher than the remaining woundtrack it gets adjusted down to minimum of zero. 

Example: Actor Ben has a Woundtrack of 5 and 0 Toughness. 
He takes 5 Damage and thus suffers a Deadly Wound with a Value of 3.   Current Woundtrack is 0 adding 3 does not exceed the Woundtrack. The Wound is added as { "Deadly Wound" : 3 } 
Actor Ben takes an additional 6 Damage and suffers another Deadly Wound with a Value of 3. Current Woundtrack is 3 adding 3 exceeds the Woundtrack so the wound gets its value adjusted to 2 which exactly fills it. The wound is added as  { "Deadly Wound" : 2 } 
Actor Ben takes another point of Damage and suffers a Minor Wound with a Value of 1. Current Woundtrack is 5 adding 1 exceeds the the Woundtrack so the Wound gets its value adjusted to 0 which leaves the Track exactly filled. The wound is added as { "Minor Wound" : 0 }

Using the Plus sign on the Character Sheet does not use this Logic since it is only application is in the ApplyDamage() function.

In Terms of Game Rules we only need to know the Last type of wound an Actor took for Death Tests, Talents etc.

We can deprecate wound object and its array, replacing them with a simple lastWoundReceived enum or string field. The ApplyDamage() Function now just changes lastWoundReceived depending on the woundtype it is already evalutating and edits the health.wounds.value attribute directly instead of adding Objects to the Wounds array.

**Comment by TrickyDUK** [comment]
I think that the check for exceeding the max wounds when using the + button (replicating the apply damage function from chat card) plus the ability to manually edit the wound value, which will allow players to implement the various scenarios created by the Wounds, Resting and Medic Talent, addresses this issue pragmatically.

**Comment by Kasyks** [comment]
TrickyDUK if you heal a wound, you heal 1 "point" from track but also the the type of wound is changed - and in this way is was implemented.
So when you heal 1 point from deadly wound (3) then it become serious wound (2) etc. 

from this what you say you want to heal 1 point from deadly wound(3) and after that have deadly wound(2) which is incorrect.

Please take a look at the Medic talent, in the second part is explained that you heal a severity of wounds   - Medic allow reduce severity by 2 when normal rest heal only reduce severity by one.

**Comment by TrickyDUK** [comment]
> TrickyDUK if you heal a wound, you heal 1 "point" from track but also the the type of wound is changed - and in this way is was implemented. So when you heal 1 point from deadly wound (3) then it become serious wound (2) etc.
> 
> from this what you say you want to heal 1 point from deadly wound(3) and after that have deadly wound(2) which is incorrect.
> 
> Please take a look at the Medic talent, in the second part is explained that you heal a severity of wounds - Medic allow reduce severity by 2 when normal rest heal only reduce severity by one.

Understand that is what the Medic Talent says, but the Resting rules alone don't say to reduce the severity nor does consuming a Sphere of Aqua Ghyranis. Also it specifically says that when you receive a Deadly Wound but only have 1 space left on Wound track, you should still record a Deadly Wound (with a value of 1). It seems that the Medic Talent is an exception and not only reduces the Wound value, but also the Wound severity.

I think regardless of the interpretation of the rules, simply allowing the value to be changed without having to change the severity is the pragmatic solution and allows for different scenarios to handled at the table.

**Comment by Kasyks** [comment]
"...If you succeed on the Test, the ally’s Wound severity reduces two steps **instead of one at the end of the Rest**..." For me there is no doubts that severity always is dropped.

But I agreed that there is a problem how to treat wounds without full amount of "wound points" because there was not enough wounds to mark, like deadly(2) or serious(1). 
deadly(2)->serious(1)->wound healed
or
deadly(2)->serious(1)->minor(1)->wounds healed. 

But the problem is in general with this book is that many things are split between different places/chapters and you have to find them and join "dots" to have whole view which is irritating ;/.
