### ISSUE TITLE
[Soulbound system] Target Armour value applied to 2 times to damage in different moments

### ISSUE THREAD

**Issue by Kasyks** [moo-man/AoS-Soulbound-FoundryVTT#90]
First time when damage roll -> chat
Second time when applied to a token from chat menu (apply damage/double damage)

**Comment by TrickyDUK** [comment]
I have to say that I did like the previous version where you got the break down of the damage. For example, this attack (which was a test against Armour 1) 
![image](https://user-images.githubusercontent.com/17655647/145694937-3db8b63b-defe-44c2-a0ad-3dd5e15e046b.png)
would show something like:
Damage: [n + S] 2 + 4 = 6
_less_ Armour [1] = 5
Note that I am not disagreeing with issue raised, just saying that while looking into this issue, it may be an opportunity to add the detail back in so that players can see how the final damage has been calculated.

**Comment by moo-man** [comment]
Should be possible, but it's not relevant to this issue.

Armour shouldn't be applied before the actual application of damage (it does currently, which is this bug)

**Comment by TrickyDUK** [comment]
Sorry, didn't mean to conflate. And you're correct, the issue is the application of Armour before the application of Damage to the Actor. Which would mean my suggestion doesn't need the 'less Amour', but still would be nice to see how the damage is being calculated. When we last played, I kept asking my players what the damage of the attack was to be sure that the damage was being correctly calculated and that led to players searching through their character sheets to find the attack. Seeing it in the chat, would just be a little improvement for me (but not essential).
